### ISSUE TITLE
CSRC application unable to connect SQL server

### ISSUE THREAD

**Issue by spuberman7** [usnistgov/CloudSecurityArchitectureTool#4]
Installed MS SQL Server 2012, Created the local server  "DESKTOP-test1", Created the database "ModelDB", Ran both SQL scripts in database "ModelDB" successfully.  Tested it by executing the query and is able to return table and value. 

After installing CSRC application. I have trouble with connecting SQL server inside the application. CSRC application returned message "connection failed. Enter SQL server name". 

Please help. thanks

**Comment by JustKuzya** [comment]
I usually use Community Edition of the VS (2013 to be exact) and SQL Server Express.

With actual SQL Server you may need to make sure that the connection string is working correctly for your setup SQL Express allows to use same machine name, SQL Server is not that easy. The easiest thing would be to pull out a connection string sample from the SQL Serve Instance of the database you have set up for the Rubik’s Cube and use it in the code instead of the existing one.
DC

**Comment by spuberman7** [comment]
hey man, thanks, 

1. would you please more information about  Community Edition of the VS (2013 to be exact) and SQL Server Express.? where can i download it?
2. can you elaborate more in detail?  "a connection string sample from the SQL Server Instance of the database"



 you have set up for the Rubik’s Cube and use it in the code instead of the existing one.

**Comment by JustKuzya** [comment]
Microsoft usually aggressively pushes their latest toolsets. All URLs I had bookmarked in the past, now apparently point to VS 2017 Express – well, MSFT needs to make money by collecting user data and pushing everyone to use Azure – their right with the tools given out for free. The VS should not be your problem though.

If VS 2010 Pro has [SQL Server] or [Data Management] console, you can try to compose the connection string right there from the console inside of the VS2010 to your SQL Server instance. I have hard time figuring out how 2010 UI used to look like online to guide you more precisely. ☹

I know that in Data Management Studio (SQL Express free tool) I can “right-click” on the database and look up connection string in the menu launched dialog. Hope that helps. BTW, you might also need to comment out the connection string that builds connection string. I’m afraid it assumed that user uses free SQL Express, which associates DB instance name with the machine name.
DC

**Comment by spuberman7** [comment]
thank y'all for the help. I got it.
